#!/usr/bin/env ansible-playbook
---

- hosts: '!poweroff'
  gather_facts: True
  tasks: [ group_by: { key: 'debian-{{ ansible_distribution_release }}' } ]
  tags: always

- hosts: debian-stretch:debian-jessie:debian-wheezy:debian-precise:debian-trusty
  gather_facts: False
  become: True
  tags: epi

  vars:

    hold_search:
      epi:
        - &epi ?and(?maintainer(epiconcept), ?installed)
      percona: 
        - &percona ~i^percona-xtrabackup$
      default_to:
        - *epi
      all:
        - *epi
        - *percona

  roles: [ { role: apt-hold } ]
    
  tasks: &tasks

    - apt_hold:
        hold: '{{ hold | default(True) }}'
        search: '{{ search | default(hold_search.default_to) }}'
        notfoundok: '{{ notfoundok | default(False) }}'
      
    - debug: { var: apt_hold }
      when: show | default(False) | bool and apt_hold.diff is defined

    - debug: { var: apt_hold.diff }
      when: not show | default(False) | bool and apt_hold.diff is defined

- hosts: 'debian-jessie:&g_mysql:!all'
  gather_facts: False
  become: True
  tags: percona

  vars:

    hold_search:
      default_to:
        - *percona

  tasks: *tasks
