#!/usr/bin/env ansible-playbook
---

- hosts: '!poweroff'
  gather_facts: True
  tasks: [ group_by: { key: 'debian-{{ ansible_distribution_release }}' } ]
  tags: always

- hosts: 'debian-jessie:&g_mysql'
  gather_facts: False
  become: True

  vars:

    # https://www.percona.com/blog/2016/10/13/new-signing-key-for-percona-debian-and-ubuntu-packages/
    keyservers: [ keys.gnupg.net, keyserver.ubuntu.com ]
    keyserver: &keyserver '{{ keyservers[0] }}'
    # http://superuser.com/questions/620765/sudo-apt-key-adv-keyserver-keyserver-ubuntu-com-recv-7f0ceb10-command-return
    keyurl: &keyurl http://keyserver.ubuntu.com/pks/lookup?op=get&search=0x9334A25F8507EFA5

  tasks:

    - { name: install percona key, apt_key: { url: *keyurl }}

    # can't get this to work
    - name: install percona key
      environment: { http_proxy: '{{ http_proxy }}' }
      apt_key: { keyserver: *keyserver, id: 8507EFA5 }
      when: False
